from schemas.assessment import Question, QuestionCategory, QuestionType, Option


def get_all_questions() -> list[Question]:
    return [
        Question(
            id="att_01",
            category=QuestionCategory.attachment,
            text="When my partner needs space or time alone, I typically feel...",
            sub_text="Reflect on your most recent relationship or current relationship",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Deeply unsettled and anxious"),
                Option(value=1, label="Somewhat worried but can manage"),
                Option(value=2, label="Neutral — I understand they need space"),
                Option(value=3, label="Comfortable and secure"),
                Option(value=4, label="Relieved — I appreciate the independence"),
            ],
            weight=1.2,
        ),
        Question(
            id="att_02",
            category=QuestionCategory.attachment,
            text="How often do you find yourself checking if your partner is happy with you?",
            sub_text="Consider your general pattern, not just one incident",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost constantly — it's on my mind all day"),
                Option(value=1, label="Very frequently throughout the day"),
                Option(value=2, label="Occasionally when things feel uncertain"),
                Option(value=3, label="Rarely — only if something specific happens"),
                Option(value=4, label="Almost never — I trust the connection"),
            ],
            weight=1.3,
            reverse_scored=True,
        ),
        Question(
            id="att_03",
            category=QuestionCategory.attachment,
            text="During a disagreement, your instinct is to...",
            type=QuestionType.multiple_choice,
            options=[
                Option(value=0, label="Pursue the conversation even if it escalates"),
                Option(value=1, label="Seek reassurance that you're still loved"),
                Option(value=2, label="Take a short break and then return"),
                Option(value=3, label="Work through it calmly together"),
                Option(value=4, label="Withdraw completely until you feel ready"),
            ],
            weight=1.4,
        ),
        Question(
            id="att_04",
            category=QuestionCategory.attachment,
            text="Emotional intimacy in relationships makes me feel...",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Terrified — closeness feels dangerous"),
                Option(value=1, label="Uncomfortable and exposed"),
                Option(value=2, label="Slightly anxious but I push through"),
                Option(value=3, label="Safe and valued"),
                Option(value=4, label="Deeply nourished and fulfilled"),
            ],
            weight=1.2,
        ),
        Question(
            id="att_05",
            category=QuestionCategory.attachment,
            text="When your partner doesn't reply quickly to a message, your first thought is...",
            type=QuestionType.multiple_choice,
            options=[
                Option(value=0, label="They must be angry or pulling away"),
                Option(value=1, label="Did I say something wrong?"),
                Option(value=2, label="They're probably just busy"),
                Option(value=3, label="No particular thought — I trust them"),
                Option(value=4, label="I barely notice until I see the reply"),
            ],
            weight=1.0,
        ),
        Question(
            id="att_06",
            category=QuestionCategory.attachment,
            text="How easily can you ask for help or support from your partner?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Extremely difficult — I feel like a burden"),
                Option(value=1, label="Hard — I worry about being judged"),
                Option(value=2, label="Somewhat difficult but possible"),
                Option(value=3, label="Mostly comfortable"),
                Option(value=4, label="Very easy — they're my safe person"),
            ],
            weight=1.1,
        ),
        Question(
            id="att_07",
            category=QuestionCategory.attachment,
            text="How unpredictable would you say your emotional responses to your partner are?",
            sub_text="Honesty here creates the most helpful analysis",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Very unpredictable — I swing between extremes"),
                Option(value=1, label="Often inconsistent"),
                Option(value=2, label="Sometimes inconsistent"),
                Option(value=3, label="Mostly predictable and stable"),
                Option(value=4, label="Very consistent and grounded"),
            ],
            weight=1.5,
            reverse_scored=True,
        ),
        Question(
            id="gott_01",
            category=QuestionCategory.gottman,
            text="During arguments, how often do you find yourself saying things like 'You always...' or 'You never...'?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Very frequently — it's my natural pattern"),
                Option(value=1, label="Often — especially when hurt"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Rarely"),
                Option(value=4, label="Almost never — I address specific behaviors"),
            ],
            weight=1.4,
            reverse_scored=True,
        ),
        Question(
            id="gott_02",
            category=QuestionCategory.gottman,
            text="When your partner raises a concern, how often do you feel the need to explain or defend yourself before listening?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost always — I feel attacked"),
                Option(value=1, label="Frequently"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Occasionally"),
                Option(value=4, label="Rarely — I try to hear them first"),
            ],
            weight=1.3,
            reverse_scored=True,
        ),
        Question(
            id="gott_03",
            category=QuestionCategory.gottman,
            text="In the past month, how often have you felt a sense of superiority or contempt toward your partner's choices or opinions?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Frequently — I often think they're wrong"),
                Option(value=1, label="Sometimes"),
                Option(value=2, label="Occasionally"),
                Option(value=3, label="Rarely"),
                Option(value=4, label="Almost never — I deeply respect them"),
            ],
            weight=1.6,
            reverse_scored=True,
        ),
        Question(
            id="gott_04",
            category=QuestionCategory.gottman,
            text="When a conversation becomes too difficult, how often do you completely shut down or go silent?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Very often — I can't continue"),
                Option(value=1, label="Frequently"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Rarely — I try to stay present"),
                Option(value=4, label="Almost never"),
            ],
            weight=1.4,
            reverse_scored=True,
        ),
        Question(
            id="gott_05",
            category=QuestionCategory.gottman,
            text="Thinking about your last week together — what was the approximate ratio of positive to negative interactions?",
            type=QuestionType.multiple_choice,
            options=[
                Option(value=0, label="Mostly negative — more conflict than connection"),
                Option(value=1, label="About equal — balanced but tense"),
                Option(value=2, label="Slightly more positive — around 2:1"),
                Option(value=3, label="Mostly positive — around 3:1 or 4:1"),
                Option(value=4, label="Overwhelmingly positive — 5:1 or better"),
            ],
            weight=1.5,
        ),
        Question(
            id="gott_06",
            category=QuestionCategory.gottman,
            text="How often do you and your partner successfully repair a conflict before it escalates?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost never — arguments spiral"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Often"),
                Option(value=4, label="Almost always — we're good at de-escalating"),
            ],
            weight=1.3,
        ),
        Question(
            id="gott_07",
            category=QuestionCategory.gottman,
            text="How well do you and your partner know each other's dreams, goals, and fears?",
            sub_text="This reflects shared meaning-making in the relationship",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Barely — we rarely go that deep"),
                Option(value=1, label="Somewhat — on surface topics"),
                Option(value=2, label="Moderately — we've had some of those conversations"),
                Option(value=3, label="Well — we talk about these things regularly"),
                Option(value=4, label="Very well — we're each other's confidants"),
            ],
            weight=1.2,
        ),
        Question(
            id="trauma_01",
            category=QuestionCategory.trauma,
            text="Did you experience significant emotional neglect or instability in your childhood home?",
            sub_text="This helps understand early relational blueprints — answer gently and honestly",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="No, my childhood felt safe and stable"),
                Option(value=1, label="Occasionally difficult but largely stable"),
                Option(value=2, label="Moderate instability at times"),
                Option(value=3, label="Significant instability or neglect"),
                Option(value=4, label="Severe and ongoing trauma or neglect"),
            ],
            weight=1.5,
        ),
        Question(
            id="trauma_02",
            category=QuestionCategory.trauma,
            text="Have you experienced interpersonal trauma (emotional, physical, or sexual harm) in a past or current relationship?",
            sub_text="You are safe here — this information is only used to tailor your support",
            type=QuestionType.multiple_choice,
            options=[
                Option(value=0, label="No, I have not"),
                Option(value=1, label="Mild emotional harm in past relationships"),
                Option(value=2, label="Significant emotional or psychological harm"),
                Option(value=3, label="Physical harm in a past relationship"),
                Option(value=4, label="Ongoing harm in my current situation"),
            ],
            weight=2.0,
        ),
        Question(
            id="trauma_03",
            category=QuestionCategory.trauma,
            text="How often do you experience hypervigilance — a state of being 'on guard' for threats even in safe situations?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Never — I generally feel safe"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Sometimes — especially in close relationships"),
                Option(value=3, label="Often"),
                Option(value=4, label="Almost constantly"),
            ],
            weight=1.4,
        ),
        Question(
            id="trauma_04",
            category=QuestionCategory.trauma,
            text="How often do you feel emotionally numb or detached from people you care about?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Never"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Often"),
                Option(value=4, label="Most of the time"),
            ],
            weight=1.3,
        ),
        Question(
            id="trauma_05",
            category=QuestionCategory.trauma,
            text="Do you notice patterns in your relationships where past trauma influences your current reactions?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="No — my past doesn't affect my present"),
                Option(value=1, label="Occasionally — sometimes I overreact"),
                Option(value=2, label="Moderately — I can see the patterns"),
                Option(value=3, label="Significantly — it affects most interactions"),
                Option(value=4, label="Severely — trauma dominates my relationship"),
            ],
            weight=1.4,
        ),
        Question(
            id="phq_01",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you had little interest or pleasure in doing things?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=1.0,
        ),
        Question(
            id="phq_02",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you felt down, depressed, or hopeless?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=1.0,
        ),
        Question(
            id="phq_03",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you had trouble concentrating on things like reading or watching television?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=1.0,
        ),
        Question(
            id="phq_04",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you been feeling nervous, anxious, or on edge?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=1.0,
        ),
        Question(
            id="phq_05",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you been unable to stop or control worrying?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=1.0,
        ),
        Question(
            id="phq_06",
            category=QuestionCategory.phq_ads,
            text="Over the past two weeks, how often have you had thoughts that you would be better off dead or of hurting yourself?",
            sub_text="If you are in immediate danger, please call a crisis line. Your safety matters.",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all"),
                Option(value=1, label="Several days"),
                Option(value=2, label="More than half the days"),
                Option(value=3, label="Nearly every day"),
            ],
            weight=2.0,
        ),
        Question(
            id="das_01",
            category=QuestionCategory.das,
            text="How often do you and your partner agree on major life decisions (finances, family, future goals)?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost never"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Occasionally"),
                Option(value=3, label="Frequently"),
                Option(value=4, label="Almost always"),
            ],
            weight=1.2,
        ),
        Question(
            id="das_02",
            category=QuestionCategory.das,
            text="How satisfied are you with your relationship overall right now?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Extremely dissatisfied"),
                Option(value=1, label="Somewhat dissatisfied"),
                Option(value=2, label="Mixed feelings"),
                Option(value=3, label="Mostly satisfied"),
                Option(value=4, label="Extremely satisfied"),
            ],
            weight=1.5,
        ),
        Question(
            id="das_03",
            category=QuestionCategory.das,
            text="How often do you and your partner engage in shared activities or interests?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost never"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Often"),
                Option(value=4, label="Very often"),
            ],
            weight=1.0,
        ),
        Question(
            id="das_04",
            category=QuestionCategory.das,
            text="How comfortable are you expressing affection (physical or verbal) with your partner?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Not at all comfortable"),
                Option(value=1, label="Slightly comfortable"),
                Option(value=2, label="Moderately comfortable"),
                Option(value=3, label="Very comfortable"),
                Option(value=4, label="Completely natural and easy"),
            ],
            weight=1.1,
        ),
        Question(
            id="das_05",
            category=QuestionCategory.das,
            text="How often do you confide in your partner about personal thoughts and feelings?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="Almost never"),
                Option(value=1, label="Rarely"),
                Option(value=2, label="Sometimes"),
                Option(value=3, label="Often"),
                Option(value=4, label="Almost always"),
            ],
            weight=1.2,
        ),
        Question(
            id="ram_01",
            category=QuestionCategory.ram,
            text="Have there been any incidents of physical harm or threats of harm in your relationship?",
            sub_text="Your safety is the highest priority — this will be handled with care",
            type=QuestionType.yes_no,
            options=[
                Option(value=0, label="No — our conflicts remain verbal"),
                Option(value=1, label="Occasional minor physical incidents"),
                Option(value=2, label="Regular physical confrontations"),
                Option(value=3, label="Yes — I fear for my physical safety"),
            ],
            weight=3.0,
        ),
        Question(
            id="ram_02",
            category=QuestionCategory.ram,
            text="Do you feel psychologically safe in your relationship — free from manipulation, coercion, or control?",
            type=QuestionType.likert,
            options=[
                Option(value=4, label="Completely safe — no concerns"),
                Option(value=3, label="Mostly safe with minor issues"),
                Option(value=2, label="Sometimes unsafe or controlled"),
                Option(value=1, label="Often feel manipulated or controlled"),
                Option(value=0, label="I am being controlled or coerced"),
            ],
            weight=2.5,
        ),
        Question(
            id="ram_03",
            category=QuestionCategory.ram,
            text="In the past 3 months, have you experienced persistent feelings of hopelessness about your future?",
            type=QuestionType.likert,
            options=[
                Option(value=0, label="No, I feel hopeful overall"),
                Option(value=1, label="Occasionally"),
                Option(value=2, label="Frequently"),
                Option(value=3, label="Almost always"),
            ],
            weight=1.8,
        ),
    ]


def get_questions_by_category(category: QuestionCategory) -> list[Question]:
    return [q for q in get_all_questions() if q.category == category]
